import React,{useState,useEffect,useRef,useCallback} from 'react';
import {watchVisible,readThread} from './refresh.js';
import ChallengeArt from './ChallengeArt.jsx';
import {DotsVertical,ArrowLeft,Reload} from '@openai/apps-sdk-ui/components/Icon';
function Links({text}){return text.split(/(https?:\/\/[^\s<>]+)/g).map((s,i)=>/^https?:\/\//.test(s)?<a key={i} href={s} target="_blank" rel="noopener noreferrer">{s}</a>:s)}
function PostImage({command,card,id}){const [src,setSrc]=useState(''),[error,setError]=useState('');const load=()=>command('image',{card,id}).then(d=>{setSrc(d.image);setError('')}).catch(e=>setError(e.message));useEffect(()=>{load()},[id,card,command]);return src?<img className="hk-image" src={src} alt="Image shared with this finding"/>:error?<p role="alert">{error} <button onClick={load}>Retry image</button></p>:<p className="hk-muted">Loading image…</p>}
function CommentMenu({onEdit,onDelete,noun}){
 const [open,setOpen]=useState(false);const root=useRef(null),trigger=useRef(null),menu=useRef(null);
 useEffect(()=>{if(!open)return;menu.current?.querySelector('button')?.focus();const outside=e=>{if(!root.current?.contains(e.target))setOpen(false)};document.addEventListener('pointerdown',outside);return()=>document.removeEventListener('pointerdown',outside)},[open]);
 function keys(e){if(e.key==='Escape'){e.preventDefault();setOpen(false);trigger.current?.focus()}else if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();const buttons=[...menu.current.querySelectorAll('button')],i=buttons.indexOf(document.activeElement);buttons[e.key==='Home'?0:e.key==='End'?buttons.length-1:(i+(e.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length]?.focus()}}
 return <div className="hk-comment-menu" ref={root} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))setOpen(false)}}><button ref={trigger} type="button" className="hk-menu-trigger" aria-label={`${noun} options`} aria-haspopup="menu" aria-expanded={open} onClick={()=>setOpen(v=>!v)} onKeyDown={e=>{if(e.key==='ArrowDown'){e.preventDefault();setOpen(true)}}}><DotsVertical width={20} height={20} aria-hidden="true"/></button>{open&&<div className="hk-menu-popup" role="menu" aria-label={`${noun} actions`} ref={menu} onKeyDown={keys}><button type="button" role="menuitem" onClick={()=>{setOpen(false);onEdit()}}>Edit</button><button type="button" role="menuitem" className="hk-menu-delete" onClick={()=>{setOpen(false);onDelete()}}>Delete</button></div>}</div>
}
function CommentComposer({card,command,parentId=null,onPosted,onCancel}){
 const [notice,setNotice]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[text,setText]=useState(''),[image,setImage]=useState(null),[reading,setReading]=useState(false);
 const composer=useRef(null),file=useRef(null),pending=useRef(null),lock=useRef(false);
 useEffect(()=>{if(parentId)composer.current?.focus()},[parentId]);
 async function choose(e){const f=e.target.files?.[0];setError('');setImage(null);pending.current=null;if(!f)return;if(!['image/png','image/jpeg','image/webp'].includes(f.type)||f.size>1000000){setError('Choose a PNG, JPEG or WebP image under 1 MB.');e.target.value='';return}setReading(true);try{const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error('Could not read this image.'));r.readAsDataURL(f)});setImage(data)}catch(e){setError(e.message)}finally{setReading(false)}}
 async function post(e){e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError('');try{if(!pending.current)pending.current={id:crypto.randomUUID(),body:{card,text,image,...(parentId?{parent_id:parentId}:{})}};const saved=await command('comment',pending.current.body,pending.current.id);pending.current=null;setText('');setImage(null);setNotice(parentId?'Reply added.':'Finding added.');if(file.current)file.current.value='';window.mobius.signal('item_created',{type:'finding'});try{await onPosted(saved)}catch(e){setNotice((parentId?'Reply':'Finding')+' saved. The discussion could not refresh; use Refresh to see it.')}}catch(e){setError(e.message)}finally{lock.current=false;setBusy(false)}}
 return <> <form className={'hk-composer'+(text||image?' hk-has-draft':'')} onSubmit={post} aria-label={parentId?"Add a reply":"Add a finding"}>
 <textarea ref={composer} id={'finding-'+card+'-'+(parentId||'root')} aria-label={parentId?"Write a reply":"Write a finding"} rows={1} maxLength={10000} value={text} disabled={busy} onChange={e=>{setText(e.target.value);pending.current=null;setNotice('')}} placeholder={parentId?"Write a reply…":"Write a finding…"}/>
 {image&&<div className="hk-attachment"><img className="hk-image" src={image} alt="Attached image preview"/><button type="button" disabled={busy} onClick={()=>{setImage(null);pending.current=null;file.current.value=''}}>Remove image</button></div>}
 <div className="hk-compose-tools"><label className="hk-attach">Attach image<input ref={file} aria-label="Attach image" type="file" accept="image/png,image/jpeg,image/webp" onChange={choose} disabled={busy||reading}/></label><div className="hk-row">{onCancel&&<button type="button" disabled={busy} onClick={onCancel}>Cancel</button>}<button className="primary" disabled={busy||reading||(!text.trim()&&!image)}>{busy?'Posting…':reading?'Reading image…':parentId?'Reply':'Post finding'}</button></div></div>
 <span className="hk-attachment-hint">PNG, JPEG or WebP · up to 1 MB</span>
 {error&&<p className="hk-compose-error" role="alert">{error}</p>}
 </form><div className="hk-comment-status" role="status">{notice}</div>
</>
}
function Comment({post:p,card,command,onChange,depth=0,fresh=false}){
 const noun=p.parent_id?'reply':'finding';
 const [replying,setReplying]=useState(false),[replies,setReplies]=useState(null),[expanded,setExpanded]=useState(false),[loadingReplies,setLoadingReplies]=useState(false);
 const [syncError,setSyncError]=useState('');
 const replyThrough=useRef(null),replyRequest=useRef(0);
 async function loadReplies(older=false){replyRequest.current++;setLoadingReplies(true);try{const d=await command('replies',{card,parent_id:p.id,...(older&&replies?.posts.length?{before:replies.posts[replies.posts.length-1].id}:{})});replyRequest.current++;if(older&&d.posts.length)replyThrough.current=d.posts.at(-1).id;setReplies(old=>older?{...d,posts:[...old.posts,...d.posts]}:d);setExpanded(true)}catch(e){setError(e.message)}finally{setLoadingReplies(false)}}

 useEffect(()=>{if(!expanded)return;return watchVisible(async signal=>{const request=++replyRequest.current;const d=await readThread(command,'replies',{card,parent_id:p.id},replyThrough.current,signal);if(!signal.aborted&&request===replyRequest.current){setReplies(d);setSyncError('')}},e=>setSyncError('Replies may be out of date. '+e.message))},[expanded,command,card,p.id]);
 const [editing,setEditing]=useState(false),[deleting,setDeleting]=useState(false),[draft,setDraft]=useState(p.text),[removeImage,setRemoveImage]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const request=useRef(null),lock=useRef(false);
 async function mutate(action){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{const body={card,id:p.id,...(action==='edit_comment'?{text:draft,original_text:p.text,remove_image:removeImage}:{})};if(!request.current)request.current={id:crypto.randomUUID(),action,body};const result=await command(request.current.action,request.current.body,request.current.id);request.current=null;setEditing(false);setDeleting(false);onChange(p.id,action==='delete_comment'?result.post:{...p,text:draft.trim(),has_image:removeImage?0:p.has_image});window.mobius.signal(action==='delete_comment'?'item_deleted':'item_updated',{type:'comment'})}catch(e){setError(e.message)}finally{lock.current=false;setBusy(false)}}
 function cancel(){setEditing(false);setDeleting(false);setError('');request.current=null}
 return <article className={'hk-post'+(fresh?' hk-new-finding':'')}><div className="hk-row"><span className="hk-avatar" aria-hidden="true">{p.deleted?'?':p.actor.replace('@','').slice(0,1).toUpperCase()}</span><strong>{p.deleted?(p.parent_id?'Reply deleted':'Finding deleted'):p.actor}</strong><time className="hk-muted" dateTime={new Date(p.created*1000).toISOString()}>{new Date(p.created*1000).toLocaleString(undefined,{year:'numeric',month:'numeric',day:'numeric',hour:'numeric',minute:'2-digit'})}</time>{p.mine&&!editing&&!deleting&&<CommentMenu noun={noun} onEdit={()=>{setDraft(p.text);setRemoveImage(false);setEditing(true);setError('');request.current=null}} onDelete={()=>{setDeleting(true);setError('');request.current=null}}/>}</div>
 {fresh&&<svg className="hk-constellation" viewBox="0 0 320 24" preserveAspectRatio="none" aria-hidden="true"><path className="hk-star-lines" pathLength="1" d="M0 20 L28 10 L112 16 L208 6 L316 14"/>{[[28,10],[112,16],[208,6],[316,14]].map(([x,y],i)=><circle className="hk-star-point" key={x} cx={x} cy={y} r={i===0?2:1.5} style={{animationDelay:`${.22+i*.32}s`}}/>)}</svg>}
 {editing?<form className="hk-edit" onSubmit={e=>{e.preventDefault();mutate('edit_comment')}}><textarea autoFocus aria-label={`Edit your ${noun}`} value={draft} maxLength={10000} disabled={busy} onChange={e=>{setDraft(e.target.value);request.current=null}}/>{!!p.has_image&&<label className="hk-remove-image"><input type="checkbox" checked={removeImage} disabled={busy} onChange={e=>{setRemoveImage(e.target.checked);request.current=null}}/> Remove attached image</label>}<div className="hk-row"><button className="primary" disabled={busy||(!draft.trim()&&(!p.has_image||removeImage))}>{busy?'Saving…':'Save changes'}</button><button type="button" onClick={cancel} disabled={busy}>Cancel</button></div></form>:<p>{p.deleted?<span className="hk-muted">This {noun} was deleted. The discussion is preserved below.</span>:<Links text={p.text}/>}</p>}
 {!!p.has_image&&(!editing||!removeImage)&&<PostImage command={command} card={card} id={p.id}/>}

 {deleting&&<div className="hk-delete-confirm"><p>Delete this {noun}{p.has_image?' and its image':''}? This cannot be undone. Replies from others will be kept.</p><div className="hk-row"><button className="hk-danger" disabled={busy} onClick={()=>mutate('delete_comment')}>{busy?'Deleting…':`Delete ${noun}`}</button><button autoFocus disabled={busy} onClick={cancel}>Keep {noun}</button></div></div>}
 {error&&<p className="hk-compose-error" role="alert">{error}</p>}{syncError&&<p className="hk-compose-error" role="status">{syncError}</p>}
 {!editing&&!deleting&&<div className="hk-reply-actions">{!p.deleted&&<button onClick={()=>setReplying(v=>!v)} aria-expanded={replying}>Reply</button>}{p.reply_count>0&&<button disabled={loadingReplies} onClick={()=>expanded?setExpanded(false):loadReplies()} aria-expanded={expanded}>{loadingReplies?'Loading…':expanded?'Hide replies':`View replies (${p.reply_count})`}</button>}</div>}
 {replying&&<div className="hk-reply-composer"><p className="hk-muted">Replying to {p.actor}</p><CommentComposer card={card} command={command} parentId={p.id} onCancel={()=>setReplying(false)} onPosted={async()=>{onChange(p.id,{...p,reply_count:(p.reply_count||0)+1});await loadReplies();setReplying(false)}}/></div>}
 {expanded&&replies&&<div className={'hk-replies'+(depth>1?' hk-replies-deep':'')} aria-label="Replies">{replies.posts.map(r=><Comment key={r.id} post={r} card={card} command={command} depth={depth+1} onChange={(id,next)=>{replyRequest.current++;setReplies(d=>({...d,posts:next?d.posts.map(item=>item.id===id?next:item):d.posts.filter(item=>item.id!==id)}));if(!next)onChange(p.id,{...p,reply_count:Math.max(0,p.reply_count-1)})}}/>)}{replies.more&&<button disabled={loadingReplies} onClick={()=>loadReplies(true)}>Older replies</button>}</div>}
 </article>
}
export default function Challenge({card,command,refresh,onBack}){
 const [detail,setDetail]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const lock=useRef(false);
 const [syncError,setSyncError]=useState('');
 const [loading,setLoading]=useState(0),[refreshNotice,setRefreshNotice]=useState('');
 const [freshId,setFreshId]=useState(null),[joinedNow,setJoinedNow]=useState(false),[briefOpen,setBriefOpen]=useState(!card.joined);
 const through=useRef(null),loadRequest=useRef(0);
 const load=useCallback(async(signal)=>{const request=++loadRequest.current;setLoading(n=>n+1);try{const d=await readThread(command,'detail',{card:card.id},through.current,signal);if(!signal?.aborted&&request===loadRequest.current){setDetail(d);setSyncError('')}}finally{setLoading(n=>n-1)}},[command,card.id]);
 useEffect(()=>{if(card.joined)return watchVisible(load,e=>setSyncError('Findings and participant counts may be out of date. '+e.message))},[card.joined,load]);
 async function enter(){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{if(!card.joined){await command('join_card',{card:card.id});setJoinedNow(true);setBriefOpen(false);await refresh()}}catch(e){setError(e.message)}finally{lock.current=false;setBusy(false)}}
 return <section className="hk-discussion" aria-label={`${card.title} discussion`}>
 <button className="hk-back" onClick={onBack}><ArrowLeft width={20} height={20} aria-hidden="true"/>Back to challenges</button>
 <div className="hk-community-title" data-challenge={card.id} style={card.color?{'--cover':card.color}:undefined}><div className="hk-community-copy"><div className="hk-challenge-label"><span className="hk-community-icon" aria-hidden="true">{card.number||card.id}</span><span className="hk-eyebrow">{card.tag}</span>{card.joined&&<span className="hk-joined-label">Joined</span>}</div><h1>{card.title}</h1><div className={"hk-about-stat"+(joinedNow?" hk-joined-now":"")}><span className="hk-members-sky" aria-hidden="true"><i/><i/><i/></span><span>{detail?.members.length??card.count} participants</span></div></div><ChallengeArt id={card.id}/></div>
 {error&&<div className="hk-error" role="alert">{error}</div>}{syncError&&<div className="hk-error" role="status">{syncError}</div>}
 <details className="hk-brief" open={briefOpen} onToggle={e=>setBriefOpen(e.currentTarget.open)}><summary>Read brief<span className="hk-muted">{card.kind==='flagship'?'Flagship bounty':'Open brief'}</span></summary><p>{card.description}</p>{card.deliverables&&<ul className="hk-deliverables">{card.deliverables.map(item=><li key={item}>{item}</li>)}</ul>}{card.prize&&<div className="hk-brief-prize"><strong>{card.prize.toLocaleString('en-GB')} BAM</strong><p>{card.format}</p></div>}{card.risk&&<p className="hk-risk"><strong>Open technical risk:</strong> {card.risk}</p>}</details>
 {card.joined&&detail&&<details className="hk-participants"><summary>Participants<span className="hk-muted">{detail.members.length}</span></summary><div className="hk-members">{detail.members.map(m=><span className="hk-member" key={m}>{m}</span>)}</div><p className="hk-muted">Findings are visible to challenge members.</p></details>}
 <div className="hk-discussion-layout"><div className="hk-feed">
 <div className="hk-feed-toolbar"><strong>Findings</strong><span className="hk-muted">Newest first</span>{card.joined&&<button className={'hk-refresh'+(loading?' hk-refreshing':'')} disabled={busy||loading>0} aria-label={loading?'Refreshing findings':'Refresh findings'} aria-busy={loading>0} title={loading?'Refreshing findings':'Refresh findings'} onClick={async()=>{setError('');setRefreshNotice('');try{await load();setRefreshNotice('Findings updated.')}catch(e){setError(e.message)}}}><Reload width={21} height={21} aria-hidden="true"/></button>}<span className="hk-sr-only" role="status">{loading?'Refreshing findings…':refreshNotice}</span></div>
 {!card.joined?<div className="hk-panel hk-empty"><h3>Join to see findings.</h3><p className="hk-muted">Become a member to see everyone taking part and their posts, images, and findings.</p><button className="primary" disabled={busy} onClick={enter}>Join challenge</button></div>:detail?<>
 <CommentComposer card={card.id} command={command} onPosted={async saved=>{await load();setFreshId(saved.id)}}/>

 {detail.posts.length===0?<div className="hk-panel hk-empty"><h3>Start the conversation.</h3><p className="hk-muted">Share your first result, ask a question, or show what you are working on.</p></div>:detail.posts.map(p=><Comment key={p.id} fresh={p.id===freshId} post={p} card={card.id} command={command} onChange={(id,next)=>{loadRequest.current++;setDetail(d=>({...d,posts:next?d.posts.map(item=>item.id===id?next:item):d.posts.filter(item=>item.id!==id)}))}}/>)}{detail.more&&<button onClick={async()=>{try{loadRequest.current++;const next=await command('detail',{card:card.id,before:detail.posts[detail.posts.length-1].id});loadRequest.current++;if(next.posts.length)through.current=next.posts.at(-1).id;setDetail(d=>({...next,posts:[...d.posts,...next.posts.filter(p=>!d.posts.some(old=>old.id===p.id))]}))}catch(e){setError(e.message)}}}>Older findings</button>}
 </>:<div className="hk-panel"><p>Loading discussion…</p></div>}
 </div></div></section>
}
