import React,{useEffect,useRef,useState,useCallback} from 'react';
import Challenge from './Challenge.jsx';
import Rewards from './Rewards.jsx';
import ChallengeArt from './ChallengeArt.jsx';
import {eventHost,watchVisible} from './refresh.js';
import {CSS} from './theme.js';
export default function App({appId,token}){
 const [selected,setSelected]=useState(null),[page,setPage]=useState('challenges');
 const navRef=useRef(null),opening=useRef(false);
 useEffect(()=>()=>navRef.current?.close(),[]);
 async function openChallenge(id){
  if(opening.current)return;opening.current=true;
  let h;h=window.mobius.nav.open('hackaton-challenge',{onBack:()=>{navRef.current=null;setSelected(null)},onForward:()=>{navRef.current=h;setSelected(id)}});
  navRef.current=h;const {status}=await h.outcome;opening.current=false;
  if(navRef.current!==h){h.close();return}
  if(status!=='owned'){navRef.current=null;setError('Could not open the discussion. Please try again.');return}
  setSelected(id);window.scrollTo(0,0);
 }
 function closeChallenge(){navRef.current?.close();navRef.current=null;setSelected(null)}
 const [ctx,setCtx]=useState(null),[state,setState]=useState(null),[host,setHost]=useState(''),[hostDraft,setHostDraft]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[rules,setRules]=useState(false);
 const activeHost=useRef(host),stateRequest=useRef(0),ready=useRef(false);activeHost.current=host;
 const [syncError,setSyncError]=useState('');
 const call=useCallback(async(path,body,signal)=>{const r=await fetch(`/api/apps/${appId}/service/${path}`,{method:body?'POST':'GET',signal,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error(d.error||d.detail||'Unable to connect. Please retry.');return d},[appId,token]);
 const command=useCallback((action,body={},request_id=crypto.randomUUID(),signal)=>call('command',{host,action,body,request_id},signal),[host,call]);
 const refresh=useCallback(async(signal)=>{const request=++stateRequest.current;const next=await command('state',{},undefined,signal);if(activeHost.current===host&&request===stateRequest.current&&!signal?.aborted){setState(next);setSyncError('');if(!ready.current){ready.current=true;window.mobius.signal('app_ready',{item_count:next.cards.length})}}},[command,host]);
 const fail=e=>{setError(e.message);window.mobius.signal('error',{message:e.message,source:'hackaton'})};
 useEffect(()=>{let live=true;(async()=>{try{const c=await call('context');const saved=await window.mobius.storage.get('event-host.json');if(live){setCtx(c);setHost(eventHost(saved,c));setHostDraft(eventHost(saved,c))}}catch(e){if(live)fail(e)}})();return()=>{live=false}},[call]);
 const watchBoard=!!host&&page==='challenges'&&(!selected||!state?.cards?.find(c=>c.id===selected)?.joined);
 useEffect(()=>{if(watchBoard)return watchVisible(refresh,e=>setSyncError(e.message))},[watchBoard,refresh]);
 async function connectHost(value){setBusy(true);setError('');try{await window.mobius.storage.set('event-host.json',{host:value});if(value===host){await refresh()}else{stateRequest.current++;activeHost.current=value;setState(null);setSyncError('');setHost(value);setHostDraft(value);setRules(false);closeChallenge()}}catch(e){fail(e)}finally{setBusy(false)}}
 async function act(action){setBusy(true);setError('');try{await command(action);await refresh();if(action==='accept')setRules(false)}catch(e){fail(e)}finally{setBusy(false)}}
 return <div className={"hk"+((rules||state&&!state.accepted)?" hk-rules-page":"")}><style>{CSS}</style><header><span className="hk-brand"><span className="hk-brand-mark" aria-hidden="true"><i/><i/><i/><i/></span>HACKATON / 2026</span><span className="hk-tag">{ctx?.identity.handle||'Möbius community'}</span></header><main><nav className="hk-seg" aria-label="Event pages">{["challenges","rewards"].map(tab=><button key={tab} aria-current={page===tab?"page":undefined} onClick={()=>{closeChallenge();setRules(false);setPage(tab)}}>{tab==='rewards'?'Rewards':'Challenges'}</button>)}</nav>{ctx&&host&&<div className={'hk-event-host'+(host!==ctx.event_host?' hk-other-event':'')}><div><strong>{host===ctx.event_host?'Shared Hackaton event':'Separate event selected'}</strong><span>{host}</span>{host!==ctx.event_host&&<p>This event has its own comments and participants. Switching keeps its data intact.</p>}</div>{host!==ctx.event_host&&<button disabled={busy} onClick={()=>connectHost(ctx.event_host)}>Use shared event</button>}</div>}{syncError&&<div className="hk-error" role="status">Could not update the event. Counts may be out of date. {syncError} <button onClick={()=>refresh().catch(e=>setSyncError(e.message))}>Retry</button></div>}{error&&<div className="hk-error" role="alert">{error} <button onClick={()=>ctx?refresh().catch(fail):location.reload()}>Retry</button></div>}
 {page==='rewards'?<Rewards/>:selected&&state?.cards?.find(c=>c.id===selected)?<Challenge key={host+selected} card={state.cards.find(c=>c.id===selected)} command={command} refresh={refresh} onBack={closeChallenge}/>:!state?<section className="hk-hero"><div className="hk-eyebrow">Hackaton 2026</div><h1>Hackaton <em>2026.</em></h1><p>{error?'Connect your Möbius account to enter the event.':'Connecting to your Möbius account…'}</p></section>:!state.joined?<section className="hk-hero"><div className="hk-eyebrow">Hackaton 2026</div><h1>Build something.<br/><em>Share what you learn.</em></h1><p>Welcome to Hackaton 2026. Pick a challenge, build alongside other makers, and share what you discover.</p><button className="primary" disabled={busy} onClick={()=>act('join')}>{busy?'Joining…':'Join Hackaton 2026'}</button><div className="hk-meta"><span>01 / Join the event</span><span>02 / Read the rules</span><span>03 / Take a challenge</span></div></section>:!state.accepted||rules?<><div className="hk-heading"><div><div className="hk-eyebrow">Before we build</div><h1>The ground rules.</h1><p className="hk-muted">Placeholder rules · final event guidelines are coming.</p></div></div><div className="hk-stack">{state.rules.map((r,i)=><section className="hk-panel" key={r.title}><div className="hk-eyebrow">0{i+1}</div><h3>{r.title}</h3><p>{r.text}</p></section>)}</div><div className="hk-heading"><button className="primary" disabled={busy} onClick={()=>state.accepted?setRules(false):act('accept')}>{state.accepted?'Back to challenges':'Continue to challenges'}</button></div></>:<><section className="hk-board-heading"><div><h1>Good questions.<br/><em>Real experiments.</em></h1><p>Pick a brief. Build together. Share what you discover.</p></div><button onClick={()=>setRules(true)}>Event rules</button></section><div className="hk-board-note"><strong>Your next challenge</strong><span>{state.cards.length} sample briefs · {state.cards.filter(c=>c.joined).length} joined</span></div><div className="hk-grid">{state.cards.map(c=><button type="button" className={"hk-card hk-card-link"+(c.joined?" hk-card-joined":"")} data-challenge={c.id} key={host+c.id} onClick={()=>openChallenge(c.id)} aria-label={`Open ${c.title}`}><span className="hk-card-top"><span className="hk-eyebrow">{c.tag}</span><span className="hk-number">{c.id}</span>{c.joined&&<span className="hk-joined-label">Joined</span>}</span><ChallengeArt id={c.id}/><span className="hk-card-title">{c.title}</span><span className="hk-card-desc">{c.description.replace(/^Sample challenge: /,'').replace(/^./,s=>s.toUpperCase())}</span><span className="hk-card-footer"><span>{c.count} joined</span><span className="hk-card-cta">{c.joined?'Open discussion':'Read brief'}<span aria-hidden="true" className="hk-entry-arrow"/></span></span></button>)}</div></>}
 {ctx&&!selected&&page==='challenges'&&<details className="hk-settings"><summary>Event host · {host}</summary><p>The shared Hackaton event is {ctx.event_host}. An alternate host opens a separate event; it does not combine comments or memberships. Previous local data remains on its original host ({ctx.host}).</p><form onSubmit={async e=>{e.preventDefault();setError('');try{const value=hostDraft.trim().replace(/^https:\/\//,'').replace(/\/$/,'').toLowerCase();if(!/^[a-z0-9][a-z0-9.-]+\.[a-z]{2,}$/.test(value))throw Error('Enter a hostname, without a path.');await connectHost(value)}catch(e){fail(e)}}}><input aria-label="Organizer hostname" value={hostDraft} onChange={e=>setHostDraft(e.target.value)}/><button disabled={busy}>Connect</button></form></details>}<footer className="hk-footer"><span>Hackaton 2026 · Science & technology</span></footer></main></div>
}
